### ISSUE TITLE
Run WATS on develop branch of cf-deployment

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/runtime-ci#9]
Since we have a GCP Windows stemcell that internal users can access, it would be really helpful if we ran WATs on the develop branch of cf-deployment to block promoting to master.

We just ran into an issue where our local usage of cf-deployment worked and a PR was accepted, but a downstream consumer's (loggregator) environment became unhealthy because they pulled in the develop branch. Luckily they caught the problem before the merge into master.

We have examples on how to set up WATs here:
- https://github.com/cloudfoundry-incubator/greenhouse-ci/blob/master/tasks/run-wats.yml
- https://github.com/cloudfoundry/wats/blob/master/scripts/run_wats.sh

I think we paired on this when we got the windows operations file into cf-deployment and it seemed like we were able to get WATs running pretty easily in one of your environments. Greenhouse would definitely be able to help out with getting this set up.

Thanks!

**Comment by dsabeti** [comment]
Hey @sunjayBhatia. We've had a story to do this for a while, but it keeps getting pushed off. Right now it looks like we'll get to it next week, hopefully: https://www.pivotaltracker.com/story/show/136001573

**Comment by sunjayBhatia** [comment]
@dsabeti ah i shouldve checked tracker first, ill close this out
